#!/bin/bash

. /home/pi/rpi-resolution_checker/.credentials

SERVER="smtp://smtp.gmail.com:25"

/usr/bin/curl --connect-timeout 15 -v --insecure $SERVER -u $USER:$PASS --mail-from $FROM --mail-rcpt $TO -T /home/pi/rpi-resolution_checker/alert_email --ssl -o ./output_log 2>&1 | tee logfile
